#!/usr/bin/env bash
# ==============================================================================
# APM Lock File helpers (Bash)
#
# Provides write_apm_lock and read_apm_lock functions for creating and reading
# .apm.lock.yaml files.  These track which APM version, mode, and provider
# bundle was installed into a consumer repository.
#
# No external YAML tools are required — the file is written and parsed with
# printf and grep/sed.
#
# Part of the Two-Mode Install System (Phase 2).
# Source this file before calling the functions:
#   source scripts/lib/apm-lock.sh
# ==============================================================================

set -euo pipefail

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
readonly APM_LOCK_FILENAME=".apm.lock.yaml"
readonly APM_LOCK_SCHEMA="https://ssg-ai-backbone.io/schemas/apm-lock/v1"
readonly APM_LOCK_PACKAGE="ssg-ai-backbone"

# ---------------------------------------------------------------------------
# write_apm_lock
# ---------------------------------------------------------------------------
# Write or update .apm.lock.yaml
#
# Usage:
#   write_apm_lock <path> <version> <mode> <provider> <archive> [checksum]
#
# Arguments:
#   path      — directory where .apm.lock.yaml will be written
#   version   — APM version string (e.g. "0.0.1")
#   mode      — "standard" or "expandable"
#   provider  — provider adapter name (e.g. "github-copilot")
#   archive   — archive filename (e.g. "ssg-ai-backbone-copilot.tar.gz")
#   checksum  — optional SHA-256 hash prefixed with "sha256:"
#
# If the lock file already exists, installed_at is preserved from the
# existing file.  All other fields are overwritten.
# ---------------------------------------------------------------------------
write_apm_lock() {
    local dest_dir="$1"
    local version="$2"
    local mode="$3"
    local provider="$4"
    local archive="$5"
    local checksum="${6:-}"

    # Validate mode
    if [[ "$mode" != "standard" && "$mode" != "expandable" ]]; then
        echo "ERROR: mode must be 'standard' or 'expandable', got '$mode'" >&2
        return 1
    fi

    local lock_file="${dest_dir}/${APM_LOCK_FILENAME}"
    local now
    now="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

    # Preserve installed_at from existing lock file
    local installed_at="$now"
    if [[ -f "$lock_file" ]]; then
        local existing
        existing="$(grep -E '^installed_at:' "$lock_file" | sed 's/^installed_at:[[:space:]]*"\{0,1\}\([^"]*\)"\{0,1\}/\1/' || true)"
        if [[ -n "$existing" ]]; then
            installed_at="$existing"
        fi
    fi

    cat > "$lock_file" <<EOF
# APM Lock File — do not edit manually
# Generated by install-apm-bundle
schema: ${APM_LOCK_SCHEMA}
version: "${version}"
mode: ${mode}
provider: ${provider}
installed_at: "${installed_at}"
updated_at: "${now}"
source:
  package: ${APM_LOCK_PACKAGE}
  archive: ${archive}
  checksum: "${checksum}"
EOF
}

# ---------------------------------------------------------------------------
# read_apm_lock
# ---------------------------------------------------------------------------
# Read .apm.lock.yaml and export APM_LOCK_* variables.
#
# Usage:
#   read_apm_lock <path>
#
# Exported variables on success:
#   APM_LOCK_SCHEMA, APM_LOCK_VERSION, APM_LOCK_MODE, APM_LOCK_PROVIDER,
#   APM_LOCK_INSTALLED_AT, APM_LOCK_UPDATED_AT, APM_LOCK_PACKAGE,
#   APM_LOCK_ARCHIVE, APM_LOCK_CHECKSUM
#
# Returns:
#   0 — lock file found and parsed
#   1 — lock file not found
# ---------------------------------------------------------------------------
read_apm_lock() {
    local dest_dir="$1"
    local lock_file="${dest_dir}/${APM_LOCK_FILENAME}"

    if [[ ! -f "$lock_file" ]]; then
        return 1
    fi

    # Helper: extract a top-level scalar (handles quoted and unquoted values)
    _yaml_value() {
        local key="$1"
        local val
        val="$(grep -E "^${key}:" "$lock_file" | head -1 | sed "s/^${key}:[[:space:]]*//" | sed 's/^"//;s/"$//' | tr -d '\r')"
        echo "$val"
    }

    # Helper: extract a nested scalar under a parent key
    _yaml_nested_value() {
        local parent="$1"
        local key="$2"
        local val
        val="$(sed -n "/^${parent}:/,/^[^[:space:]]/{ /^[[:space:]]*${key}:/p; }" "$lock_file" \
            | head -1 \
            | sed "s/^[[:space:]]*${key}:[[:space:]]*//" \
            | sed 's/^"//;s/"$//' \
            | tr -d '\r')"
        echo "$val"
    }

    export APM_LOCK_SCHEMA="$(_yaml_value schema)"
    export APM_LOCK_VERSION="$(_yaml_value version)"
    export APM_LOCK_MODE="$(_yaml_value mode)"
    export APM_LOCK_PROVIDER="$(_yaml_value provider)"
    export APM_LOCK_INSTALLED_AT="$(_yaml_value installed_at)"
    export APM_LOCK_UPDATED_AT="$(_yaml_value updated_at)"
    export APM_LOCK_PACKAGE="$(_yaml_nested_value source package)"
    export APM_LOCK_ARCHIVE="$(_yaml_nested_value source archive)"
    export APM_LOCK_CHECKSUM="$(_yaml_nested_value source checksum)"

    return 0
}
