<#
.SYNOPSIS
    APM Lock File helpers (PowerShell)

.DESCRIPTION
    Provides Write-ApmLock and Read-ApmLock functions for creating and reading
    .apm.lock.yaml files.  These track which APM version, mode, and provider
    bundle was installed into a consumer repository.

    No external YAML modules are required — the file is written and parsed
    with plain string formatting and regex.

.NOTES
    Part of the Two-Mode Install System (Phase 2).
    Source this file with `. scripts/lib/apm-lock.ps1` before calling the
    functions.
#>

Set-StrictMode -Version Latest

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
$script:APM_LOCK_FILENAME = '.apm.lock.yaml'
$script:APM_LOCK_SCHEMA   = 'https://ssg-ai-backbone.io/schemas/apm-lock/v1'
$script:APM_LOCK_PACKAGE  = 'ssg-ai-backbone'

# ---------------------------------------------------------------------------
# Write-ApmLock
# ---------------------------------------------------------------------------
function Write-ApmLock {
    <#
    .SYNOPSIS
        Creates or updates an .apm.lock.yaml file.

    .DESCRIPTION
        If the lock file does not exist, creates it with installed_at and
        updated_at set to the current UTC time.  If the file already exists,
        preserves installed_at, sets updated_at to now, and updates every
        other field.

    .PARAMETER Path
        Directory where .apm.lock.yaml will be written.

    .PARAMETER Version
        APM version string (e.g. "0.0.1").

    .PARAMETER Mode
        Install mode — either "standard" or "expandable".

    .PARAMETER Provider
        Provider adapter name (e.g. "github-copilot").

    .PARAMETER Archive
        Archive filename (e.g. "ssg-ai-backbone-copilot.tar.gz").

    .PARAMETER Checksum
        Optional SHA-256 checksum prefixed with "sha256:".
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)] [string]$Path,
        [Parameter(Mandatory)] [string]$Version,
        [Parameter(Mandatory)] [ValidateSet('standard','expandable')] [string]$Mode,
        [Parameter(Mandatory)] [string]$Provider,
        [Parameter(Mandatory)] [string]$Archive,
        [string]$Checksum = ''
    )

    $lockFile = Join-Path $Path $script:APM_LOCK_FILENAME
    $now      = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')

    # Determine installed_at — preserve from existing file when present
    $installedAt = $now
    if (Test-Path $lockFile) {
        $existing = Read-ApmLock -Path $Path
        if ($null -ne $existing -and $existing.ContainsKey('installed_at') -and $existing['installed_at']) {
            $installedAt = $existing['installed_at']
        }
    }

    $yaml = @"
# APM Lock File — do not edit manually
# Generated by install-apm-bundle
schema: $($script:APM_LOCK_SCHEMA)
version: "$Version"
mode: $Mode
provider: $Provider
installed_at: "$installedAt"
updated_at: "$now"
source:
  package: $($script:APM_LOCK_PACKAGE)
  archive: $Archive
  checksum: "$Checksum"
"@

    # Ensure trailing newline
    $yaml = $yaml.TrimEnd("`r", "`n") + "`n"

    [System.IO.File]::WriteAllText($lockFile, $yaml, [System.Text.UTF8Encoding]::new($false))

    Write-Verbose "Wrote lock file to $lockFile"
}

# ---------------------------------------------------------------------------
# Read-ApmLock
# ---------------------------------------------------------------------------
function Read-ApmLock {
    <#
    .SYNOPSIS
        Reads an .apm.lock.yaml file and returns a hashtable.

    .DESCRIPTION
        Parses the lock file using simple regex — no external YAML module
        required.  Returns $null when the file does not exist.

    .PARAMETER Path
        Directory containing .apm.lock.yaml.

    .OUTPUTS
        [hashtable] with keys: schema, version, mode, provider,
        installed_at, updated_at, package, archive, checksum.
        Returns $null if the lock file is not found.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)] [string]$Path
    )

    $lockFile = Join-Path $Path $script:APM_LOCK_FILENAME

    if (-not (Test-Path $lockFile)) {
        return $null
    }

    $content = Get-Content -Path $lockFile -Raw

    # Helper: extract a top-level scalar value (handles quoted and unquoted)
    function Get-YamlValue {
        param([string]$Text, [string]$Key)
        if ($Text -match "(?m)^${Key}:\s+`"([^`"]*)`"") {
            return $Matches[1]
        }
        if ($Text -match "(?m)^${Key}:\s+(.+)$") {
            return $Matches[1].Trim()
        }
        return ''
    }

    # Helper: extract an indented scalar under a parent key
    function Get-YamlNestedValue {
        param([string]$Text, [string]$Parent, [string]$Key)
        if ($Text -match "(?m)^${Parent}:\s*\r?\n(?:[ ]+\S[^\r\n]*\r?\n)*?[ ]+${Key}:\s+`"([^`"]*)`"") {
            return $Matches[1]
        }
        if ($Text -match "(?m)^${Parent}:\s*\r?\n(?:[ ]+\S[^\r\n]*\r?\n)*?[ ]+${Key}:\s+(.+)$") {
            return $Matches[1].Trim()
        }
        return ''
    }

    return @{
        schema       = Get-YamlValue $content 'schema'
        version      = Get-YamlValue $content 'version'
        mode         = Get-YamlValue $content 'mode'
        provider     = Get-YamlValue $content 'provider'
        installed_at = Get-YamlValue $content 'installed_at'
        updated_at   = Get-YamlValue $content 'updated_at'
        package      = Get-YamlNestedValue $content 'source' 'package'
        archive      = Get-YamlNestedValue $content 'source' 'archive'
        checksum     = Get-YamlNestedValue $content 'source' 'checksum'
    }
}
