#!/usr/bin/env python3
"""Validate GitHub Copilot three-layer architecture:
  Layer 1: .apm/ (canonical definitions — agents, skills, prompts, templates, workflows)
  Layer 2: providers/github-copilot/ (adapter: agents, prompts, instructions, docs)
  Layer 3: .github/ (runtime projection — generated by project-copilot.ps1, gitignored)
"""
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
APM = ROOT / '.apm'
PROVIDER = ROOT / 'providers' / 'github-copilot'
RUNTIME = ROOT / '.github'

errors = []
warnings = []

# --- Canonical layer: must have agents, prompts, skills, templates ---
for subdir in ['agents', 'skills', 'prompts', 'templates']:
    d = APM / subdir
    if not d.is_dir() or not any(d.iterdir()):
        errors.append(f'Missing or empty canonical directory: .apm/{subdir}/')

# --- Provider layer: must have agents, prompts, instructions ---
for subdir in ['agents', 'prompts', 'instructions']:
    d = PROVIDER / subdir
    if not d.is_dir() or not any(d.iterdir()):
        errors.append(f'Missing or empty provider directory: providers/github-copilot/{subdir}/')

# --- Provider layer: must have adapter docs ---
for doc in ['conventions.md', 'sync-map.md']:
    if not (PROVIDER / doc).exists():
        errors.append(f'Missing adapter doc: providers/github-copilot/{doc}')

# --- Canonical agents must be projected to provider layer ---
if (APM / 'agents').is_dir() and (PROVIDER / 'agents').is_dir():
    canonical_agents = {p.stem for p in (APM / 'agents').glob('*.md')}
    provider_agents = {p.stem.replace('.agent', '') for p in (PROVIDER / 'agents').glob('*.agent.md')}
    missing = canonical_agents - provider_agents
    for a in missing:
        warnings.append(f'Canonical agent without runtime projection: {a}')

# --- Canonical prompts must be projected to provider layer ---
if (APM / 'prompts').is_dir() and (PROVIDER / 'prompts').is_dir():
    canonical_prompts = {p.stem for p in (APM / 'prompts').glob('*.md')}
    provider_prompts = {p.stem.replace('.prompt', '') for p in (PROVIDER / 'prompts').glob('*.prompt.md')}
    missing = canonical_prompts - provider_prompts
    for p in missing:
        warnings.append(f'Prompt not projected to provider layer: {p}')

# --- Provider agents must have a canonical counterpart ---
if (APM / 'agents').is_dir() and (PROVIDER / 'agents').is_dir():
    canonical_agents = {p.stem for p in (APM / 'agents').glob('*.md')}
    provider_agents = {p.stem.replace('.agent', '') for p in (PROVIDER / 'agents').glob('*.agent.md')}
    orphaned = provider_agents - canonical_agents
    for a in orphaned:
        errors.append(f'Provider agent without canonical definition: {a}')

# --- Hub context: .github/copilot-instructions.md ---
if not (RUNTIME / 'copilot-instructions.md').exists():
    errors.append('Missing .github/copilot-instructions.md')

# --- Sync check: canonical workflows → provider workflow prompts ---
if (APM / 'workflows').is_dir() and (PROVIDER / 'prompts').is_dir():
    canonical_workflows = {p.stem for p in (APM / 'workflows').glob('*.yml')}
    workflow_prompts = {p.stem.replace('workflow-', '').replace('.prompt', '')
                       for p in (PROVIDER / 'prompts').glob('workflow-*.prompt.md')}

    for wf in canonical_workflows:
        if not any(wf in wp or wp in wf for wp in workflow_prompts):
            warnings.append(f'Workflow without runtime prompt: {wf}')

# --- Instruction files must have applyTo frontmatter ---
if (PROVIDER / 'instructions').is_dir():
    for instr in (PROVIDER / 'instructions').glob('*.instructions.md'):
        content = instr.read_text(encoding='utf-8')
        if 'applyTo:' not in content:
            errors.append(f'Instruction missing applyTo frontmatter: {instr.name}')

# --- Report ---
if errors:
    print(f'Copilot validation FAILED ({len(errors)} errors, {len(warnings)} warnings):')
    for e in errors:
        print(f'  ERROR: {e}')
    for w in warnings:
        print(f'  WARN:  {w}')
    sys.exit(1)

print(f'Copilot validation PASSED ({len(warnings)} warnings)')
for w in warnings:
    print(f'  WARN: {w}')
